// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/MisakaTAT/GTerm/backend/initialize"
	"github.com/MisakaTAT/GTerm/backend/services"
)

// Injectors from wire.go:

func NewApp() *App {
	httpListenerPort := initialize.InitHTTPServer()
	query := initialize.InitDatabase()
	connectionSrv := &services.ConnectionSrv{
		Query: query,
	}
	metadataSrv := &services.MetadataSrv{
		Query: query,
	}
	terminalSrv := &services.TerminalSrv{
		ConnectionSrv:    connectionSrv,
		MetadataSrv:      metadataSrv,
		HTTPListenerPort: httpListenerPort,
	}
	preferencesSrv := &services.PreferencesSrv{}
	groupSrv := &services.GroupSrv{
		Query: query,
	}
	credentialSrv := &services.CredentialSrv{
		Query: query,
	}
	websocketSrv := &services.WebsocketSrv{
		TerminalSrv: terminalSrv,
	}
	appContext := initialize.InitDefaultContext()
	fileTransferSrv := &services.FileTransferSrv{
		ConnectionSrv: connectionSrv,
		AppContext:    appContext,
	}
	app := &App{
		HTTPListenerPort: httpListenerPort,
		TerminalSrv:      terminalSrv,
		PreferencesSrv:   preferencesSrv,
		GroupSrv:         groupSrv,
		ConnectionSrv:    connectionSrv,
		MetadataSrv:      metadataSrv,
		CredentialSrv:    credentialSrv,
		WebsocketSrv:     websocketSrv,
		FileTransferSrv:  fileTransferSrv,
	}
	return app
}
